# Generated by Django 3.1.7 on 2021-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0005_auto_20210407_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_gd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_igd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_spread',
            field=models.BooleanField(default=False),
        ),
    ]
