# Generated by Django 3.1.7 on 2021-04-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0006_auto_20210407_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmodel',
            name='gd',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='igd',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='spread',
        ),
    ]
