# Generated by Django 3.1.7 on 2021-04-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0007_auto_20210407_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_gd',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_igd',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_spread',
        ),
    ]
