# Generated by Django 3.1.7 on 2021-04-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0009_resultmodel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='history',
            field=models.TextField(),
        ),
    ]
