# Generated by Django 3.1.7 on 2021-04-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0010_auto_20210408_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmodel',
            name='history',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='hv',
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='hstry_f',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='hstry_g',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='hstry_x',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='hvs',
            field=models.TextField(blank=True),
        ),
    ]
