# Generated by Django 3.1.7 on 2021-04-08 17:12

from django.db import migrations, models
import dss.models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0011_auto_20210408_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsga3model',
            name='n_offsprings',
            field=models.CharField(blank=True, default='None', max_length=16, null=10, validators=[dss.models.is_positive_int_or_None]),
        ),
    ]
