# Generated by Django 3.1.7 on 2021-04-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0012_auto_20210408_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='hvs_gens_fig',
            field=models.TextField(blank=True),
        ),
    ]
