# Generated by Django 3.1.7 on 2021-04-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0014_resultmodel_ref_dirs_fig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemmodel',
            name='nsga3_fk',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='unsga3_fk',
        ),
    ]
