# Generated by Django 3.1.7 on 2021-04-13 06:12

from django.db import migrations, models
import dss.models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0015_auto_20210412_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsga3model',
            name='ref_dirs',
            field=models.TextField(blank=True, help_text='Формат ввода:[x,y,...,z],[x,y,...,z],...,[x,y,...,z]. Формат чисел с плавающей точкой:1.2', null=True, validators=[dss.models.vals_have_same_dim]),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='xl',
            field=models.TextField(help_text='Формат ввода:[x,y,...,z],[x,y,...,z],...,[x,y,...,z]. Формат чисел с плавающей точкой:1.2', null=True, validators=[dss.models.vals_have_same_dim]),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='xu',
            field=models.TextField(help_text='Формат ввода:[x,y,...,z],[x,y,...,z],...,[x,y,...,z]. Формат чисел с плавающей точкой:1.2', null=True, validators=[dss.models.vals_have_same_dim]),
        ),
        migrations.AlterField(
            model_name='unsga3model',
            name='ref_dirs',
            field=models.TextField(blank=True, help_text='Формат ввода:[x,y,...,z],[x,y,...,z],...,[x,y,...,z]. Формат чисел с плавающей точкой:1.2', null=True, validators=[dss.models.vals_have_same_dim]),
        ),
    ]
